In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("../assets/factors.csv")
df

,Unnamed: 0,序号,类别,因子名称,计算公式/定义
0,0,1,价值类,市盈率（PE）,总市值 / 净利润(TTM)
1,1,2,价值类,市净率（PB）,总市值 / 净资产
2,2,3,价值类,企业价值倍数（EV/EBITDA）,(总市值 + 有息负债 - 现金) / EBITDA
3,3,4,价值类,市销率（PS）,总市值 / 营业收入(TTM)
4,4,5,价值类,股息率（DY）,年度分红总额 / 总市值
5,5,6,成长类,净利润增长率,(本期净利润 - 上期净利润) / |上期净利润|
6,6,7,成长类,营业收入增长率,(本期营业收入 - 上期营业收入) / |上期营业收入|
7,7,8,成长类,主营业收入,主营业收入
8,8,9,成长类,资本支出增长率,(本期购建固定资产现金支出 - 上期) / |上期值|
9,9,10,成长类,毛利增长率,(本期毛利润 - 上期毛利润) / |上期毛利润|
10,10,11,质量类,ROE,净利润 / 平均股东权益
11,11,12,质量类,资产负债率,总负债 / 总资产
12,12,13,质量类,经营活动现金流/净利润,经营性现金流净额 / 净利润
13,13,14,质量类,应收账款周转率,营业收入 / 平均应收账款余额
14,14,15,质量类,营业利润率,营业利润 / 营业收入
15,15,16,动量类,12个月收益率,过去250个交易日累计收益率（复权）
16,16,17,动量类,6个月超额收益（Alpha）,个股收益率 - 申万电子指数收益率（120日）
17,17,18,动量类,相对强弱指标（RSI_14）,14日平均涨幅 / (14日平均涨幅 + 14日平均跌幅) × 100
18,18,19,波动类,年化波动率,日收益率标准差 × √250
19,19,20,波动类,最大回撤,历史最高点至最低点的最大跌幅
20,20,21,波动类,Beta值,个股与行业指数的协方差 / 行业指数方差（250日）
21,21,22,流动性类,换手率（20日平均）,日均换手率的20日移动平均
22,22,23,流动性类,Amihud非流动性指标,日均（|收益率| / 成交额）
23,23,24,流动性类,机构持股比例变化,机构持股比例（季度变化）
24,24,25,情绪类,分析师评级变化,季度内评级上调次数 - 下调次数
25,25,26,情绪类,融资余额增长率,(本月融资余额 - 上月余额) / 上月余额
26,26,27,情绪类,龙虎榜净流入金额,月内龙虎榜机构净买入金额（买入额 - 卖出额）
27,27,28,情绪类,股东户数变化率,(本期股东户数 - 上期户数) / 上期户数
28,28,29,技术类,MACD指标,12日EMA - 26日EMA（需计算快慢线差值）
29,29,30,技术类,布林带宽度,(上轨 - 下轨) / 中轨（20日移动平均）

In [9]:
df.drop('Unnamed: 0',axis=1, inplace=True)

In [10]:
df

    序号    类别               因子名称                              计算公式/定义
0    1   价值类            市盈率（PE）                       总市值 / 净利润(TTM)
1    2   价值类            市净率（PB）                            总市值 / 净资产
2    3   价值类  企业价值倍数（EV/EBITDA）           (总市值 + 有息负债 - 现金) / EBITDA
3    4   价值类            市销率（PS）                      总市值 / 营业收入(TTM)
4    5   价值类            股息率（DY）                         年度分红总额 / 总市值
5    6   成长类             净利润增长率            (本期净利润 - 上期净利润) / |上期净利润|
6    7   成长类            营业收入增长率         (本期营业收入 - 上期营业收入) / |上期营业收入|
7    8   成长类              主营业收入                                主营业收入
8    9   成长类            资本支出增长率          (本期购建固定资产现金支出 - 上期) / |上期值|
9   10   成长类              毛利增长率            (本期毛利润 - 上期毛利润) / |上期毛利润|
10  11   质量类                ROE                         净利润 / 平均股东权益
11  12   质量类              资产负债率                            总负债 / 总资产
12  13   质量类        经营活动现金流/净利润                       经营性现金流净额 / 净利润
13  14   质量类            应收账款周转率                      营业收入 / 平均应收账款余额
14  15   质量类              营业利润率                          营业利润 / 营业收入
15  16   动量类            12个月收益率                   过去250个交易日累计收益率（复权）
16  17   动量类     6个月超额收益（Alpha）              个股收益率 - 申万电子指数收益率（120日）
17  18   动量类     相对强弱指标（RSI_14）  14日平均涨幅 / (14日平均涨幅 + 14日平均跌幅) × 100
18  19   波动类              年化波动率                       日收益率标准差 × √250
19  20   波动类               最大回撤                       历史最高点至最低点的最大跌幅
20  21   波动类              Beta值           个股与行业指数的协方差 / 行业指数方差（250日）
21  22  流动性类         换手率（20日平均）                        日均换手率的20日移动平均
22  23  流动性类       Amihud非流动性指标                      日均（|收益率| / 成交额）
23  24  流动性类           机构持股比例变化                         机构持股比例（季度变化）
24  25   情绪类            分析师评级变化                     季度内评级上调次数 - 下调次数
25  26   情绪类            融资余额增长率               (本月融资余额 - 上月余额) / 上月余额
26  27   情绪类           龙虎榜净流入金额              月内龙虎榜机构净买入金额（买入额 - 卖出额）
27  28   情绪类            股东户数变化率               (本期股东户数 - 上期户数) / 上期户数
28  29   技术类             MACD指标            12日EMA - 26日EMA（需计算快慢线差值）
29  30   技术类              布林带宽度              (上轨 - 下轨) / 中轨（20日移动平均）

In [17]:
from utils.utils import *
engine = easyConnect()
# df.drop('序号',axis=1,inplace=True)
df.rename({'类别':'category', '因子名称':'factor_name', '计算公式/定义':'definition'}, axis=1, inplace=True)

In [18]:
df

   category        factor_name                           definition
0       价值类            市盈率（PE）                       总市值 / 净利润(TTM)
1       价值类            市净率（PB）                            总市值 / 净资产
2       价值类  企业价值倍数（EV/EBITDA）           (总市值 + 有息负债 - 现金) / EBITDA
3       价值类            市销率（PS）                      总市值 / 营业收入(TTM)
4       价值类            股息率（DY）                         年度分红总额 / 总市值
5       成长类             净利润增长率            (本期净利润 - 上期净利润) / |上期净利润|
6       成长类            营业收入增长率         (本期营业收入 - 上期营业收入) / |上期营业收入|
7       成长类              主营业收入                                主营业收入
8       成长类            资本支出增长率          (本期购建固定资产现金支出 - 上期) / |上期值|
9       成长类              毛利增长率            (本期毛利润 - 上期毛利润) / |上期毛利润|
10      质量类                ROE                         净利润 / 平均股东权益
11      质量类              资产负债率                            总负债 / 总资产
12      质量类        经营活动现金流/净利润                       经营性现金流净额 / 净利润
13      质量类            应收账款周转率                      营业收入 / 平均应收账款余额
14      质量类              营业利润率                          营业利润 / 营业收入
15      动量类            12个月收益率                   过去250个交易日累计收益率（复权）
16      动量类     6个月超额收益（Alpha）              个股收益率 - 申万电子指数收益率（120日）
17      动量类     相对强弱指标（RSI_14）  14日平均涨幅 / (14日平均涨幅 + 14日平均跌幅) × 100
18      波动类              年化波动率                       日收益率标准差 × √250
19      波动类               最大回撤                       历史最高点至最低点的最大跌幅
20      波动类              Beta值           个股与行业指数的协方差 / 行业指数方差（250日）
21     流动性类         换手率（20日平均）                        日均换手率的20日移动平均
22     流动性类       Amihud非流动性指标                      日均（|收益率| / 成交额）
23     流动性类           机构持股比例变化                         机构持股比例（季度变化）
24      情绪类            分析师评级变化                     季度内评级上调次数 - 下调次数
25      情绪类            融资余额增长率               (本月融资余额 - 上月余额) / 上月余额
26      情绪类           龙虎榜净流入金额              月内龙虎榜机构净买入金额（买入额 - 卖出额）
27      情绪类            股东户数变化率               (本期股东户数 - 上期户数) / 上期户数
28      技术类             MACD指标            12日EMA - 26日EMA（需计算快慢线差值）
29      技术类              布林带宽度              (上轨 - 下轨) / 中轨（20日移动平均）

In [22]:
upsert_to_mysql(engine, 'factor_metadata', df, primary_key=['factor_name'])

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'a':[1,2,3,4],
    'b':[5,6,7,8],
    'c':[9,10,11,12],
    'd':[13,14,np.nan, np.nan]
}
)

In [3]:
df

   a  b   c     d
0  1  5   9  13.0
1  2  6  10  14.0
2  3  7  11   NaN
3  4  8  12   NaN

In [4]:
from utils.utils import easyConnect
engine = easyConnect()
df = pd.read_sql('factor_panel_data',con=engine)

08-25 22:50:20 | INFO    | utils.logger_config:_setup_logger | 📝 日志系统启动成功
08-25 22:50:20 | INFO    | utils.logger_config:_setup_logger | 📁 主日志文件: C:\Users\31021\Desktop\Quantitative_Trading\Coding\Get_Stock_Infos\logs\20250825-8.log
08-25 22:50:20 | INFO    | utils.logger_config:_setup_logger | 🔴 错误日志文件: C:\Users\31021\Desktop\Quantitative_Trading\Coding\Get_Stock_Infos\logs\20250825-8_error.log
08-25 22:50:20 | INFO    | utils.logger_config:_setup_logger | 📂 项目根目录: C:\Users\31021\Desktop\Quantitative_Trading\Coding\Get_Stock_Infos

In [5]:
df

        ts_code trade_date     factor_name  factor_value
0     000001.SZ 2024-01-02         12个月收益率     -0.268078
1     000001.SZ 2024-01-02  6个月超额收益（Alpha）     -0.121474
2     000001.SZ 2024-01-02           Beta值      1.120699
3     000001.SZ 2024-01-02          MACD指标     -0.165840
4     000001.SZ 2024-01-02         市净率（PB）      0.451400
...         ...        ...             ...           ...
8871  600519.SH 2024-06-30     经营活动现金流/净利润      0.848181
8872  600519.SH 2024-06-30           营业利润率      0.702432
8873  600519.SH 2024-06-30         营业收入增长率      0.789843
8874  600519.SH 2024-06-30           资产负债率      0.183242
8875  600519.SH 2024-06-30         资本支出增长率      0.923136

[8876 rows x 4 columns]

In [9]:
df.pivot(index=['trade_date','ts_code'], columns='factor_name', values='factor_value')

factor_name            12个月收益率  6个月超额收益（Alpha）  Amihud非流动性指标     Beta值  \
trade_date ts_code
2021-05-31 000592.SZ       NaN             NaN           NaN       NaN
2024-01-02 000001.SZ -0.268078       -0.121474           NaN  1.120699
           300750.SZ -0.301472       -0.238160           NaN  1.122721
           600096.SH -0.278996       -0.013736           NaN  1.298555
           600380.SH  0.131644        0.088287           NaN  1.010641
...                        ...             ...           ...       ...
2024-06-30 000001.SZ       NaN             NaN           NaN       NaN
           300750.SZ       NaN             NaN           NaN       NaN
           600096.SH       NaN             NaN           NaN       NaN
           600380.SH       NaN             NaN           NaN       NaN
           600519.SH       NaN             NaN           NaN       NaN

factor_name             MACD指标       ROE         主营业收入  企业价值倍数（EV/EBITDA）  \
trade_date ts_code
2021-05-31 000592.SZ       NaN       NaN           NaN                NaN
2024-01-02 000001.SZ -0.165840       NaN           NaN                NaN
           300750.SZ -3.838979       NaN           NaN                NaN
           600096.SH -0.108815       NaN           NaN                NaN
           600380.SH  0.006725       NaN           NaN                NaN
...                        ...       ...           ...                ...
2024-06-30 000001.SZ       NaN  0.053500  7.713200e+10                NaN
           300750.SZ       NaN  0.110497  1.667668e+11          17.310921
           600096.SH       NaN  0.148395  3.199294e+10           7.847779
           600380.SH       NaN  0.072720  8.234634e+09           4.527968
           600519.SH       NaN  0.181194  8.193098e+10          30.968400

factor_name             净利润增长率  市净率（PB）  ...  相对强弱指标（RSI_14）  经营活动现金流/净利润  \
trade_date ts_code                       ...
2021-05-31 000592.SZ       NaN      NaN  ...             NaN          NaN
2024-01-02 000001.SZ       NaN   0.4514  ...       46.418093          NaN
           300750.SZ       NaN   3.8248  ...       48.036367          NaN
           600096.SH       NaN   1.5974  ...       72.892677          NaN
           600380.SH       NaN   1.8412  ...       60.781266          NaN
...                        ...      ...  ...             ...          ...
2024-06-30 000001.SZ  0.733123      NaN  ...             NaN     4.394374
           300750.SZ  1.222191      NaN  ...             NaN     1.797066
           600096.SH  1.009701      NaN  ...             NaN     1.348747
           600380.SH  0.833554      NaN  ...             NaN     1.024221
           600519.SH  0.735243      NaN  ...             NaN     0.848181

factor_name           股东户数变化率  股息率（DY）     营业利润率   营业收入增长率   融资余额增长率  \
trade_date ts_code
2021-05-31 000592.SZ      NaN      NaN       NaN       NaN       NaN
2024-01-02 000001.SZ      NaN   3.0945       NaN       NaN       NaN
           300750.SZ      NaN   0.8921       NaN       NaN       NaN
           600096.SH      NaN   6.3331       NaN       NaN  0.009109
           600380.SH      NaN   1.4338       NaN       NaN -0.006387
...                       ...      ...       ...       ...       ...
2024-06-30 000001.SZ      NaN      NaN  0.416001  0.989476       NaN
           300750.SZ      NaN      NaN  0.177221  1.090575       NaN
           600096.SH      NaN      NaN  0.127562  1.308767       NaN
           600380.SH      NaN      NaN  0.241288  0.897462       NaN
           600519.SH      NaN      NaN  0.702432  0.789843       NaN

factor_name              资产负债率   资本支出增长率      龙虎榜净流入金额
trade_date ts_code
2021-05-31 000592.SZ       NaN       NaN  1.006321e+08
2024-01-02 000001.SZ       NaN       NaN           NaN
           300750.SZ       NaN       NaN           NaN
           600096.SH       NaN       NaN           NaN
           600380.SH       NaN       NaN           NaN
...                        ...       ...           ...
2024-06-30 000001.SZ  0.916255  1.618257           NaN
           300750.SZ  0.692640  0.952981           NaN
           600096.SH  0.564906  0.998012           NaN
           600380.SH  0.366682  1.153460           NaN
           600519.SH  0.183242  0.923136           NaN

[596 rows x 28 columns]

In [2]:
from utils.utils import easyConnect
engine = easyConnect()
temp = pd.read_sql('temp_joiner',con=engine)
tt = temp.pivot(index=['ts_code','trade_date'], columns='data_name', values='data_value')
tt.to_sql('temp_joiner_wide',con=engine, if_exists='replace')

08-27 17:20:27 | INFO    | utils.logger_config:_setup_logger | 📝 日志系统启动成功
08-27 17:20:27 | INFO    | utils.logger_config:_setup_logger | 📁 主日志文件: C:\Users\31021\Desktop\Quantitative_Trading\Coding\Get_Stock_Infos\logs\20250827-51.log
08-27 17:20:27 | INFO    | utils.logger_config:_setup_logger | 🔴 错误日志文件: C:\Users\31021\Desktop\Quantitative_Trading\Coding\Get_Stock_Infos\logs\20250827-51_error.log
08-27 17:20:27 | INFO    | utils.logger_config:_setup_logger | 📂 项目根目录: C:\Users\31021\Desktop\Quantitative_Trading\Coding\Get_Stock_Infos

OperationalError: (pymysql.err.OperationalError) (1170, "BLOB/TEXT column 'ts_code' used in key specification without a key length")
[SQL: CREATE INDEX ix_temp_joiner_wide_ts_code ON temp_joiner_wide (ts_code)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [3]:
from sqlalchemy import types

engine = easyConnect()

temp = pd.read_sql('temp_joiner', con=engine)

tt = temp.pivot(index=['ts_code','trade_date'],
                columns='data_name',
                values='data_value').reset_index()

# 明确类型，避免被映射成 TEXT
tt['ts_code'] = tt['ts_code'].astype(str)
tt['trade_date'] = pd.to_datetime(tt['trade_date']).dt.date  # or keep as string

tt.to_sql(
    'temp_joiner_wide',
    con=engine,
    if_exists='replace',
    index=False,   # 关键：不要把 DataFrame 的索引写到库里
    dtype={
        'ts_code': types.VARCHAR(12),      # 根据你的代码长度调整
        'trade_date': types.DATE           # 或 types.VARCHAR(10)
    },
    chunksize=50_000,   # 你有 ~75万行，分批更稳
    method='multi'
)

759438